[platformio]
default_envs = esp32_pico_borealis

[env:esp32_pico_borealis]
extends = esp32_4MB_M_base
board = pico32
board_build.flash_mode = dout ;; (dout = dual out; more compatible than qio = quad i/o)
; upload_speed = 256000 ;; or 115200 ;; or 460800 ; or 921600  (slower speeds are better when flashing without a soldered connection)
upload_speed = 921600 ;; or 115200 ;; or 460800 ; or 921600  (slower speeds are better when flashing without a soldered connection)

board_build.partitions = tools/WLED_ESP32_4MB_256KB_FS.csv

build_flags = 
  ${common.build_flags_esp32}
  ${common_mm.build_flags_S}
  -D WLED_ENABLE_SIMPLE_UI
  -D WLED_RELEASE_NAME=borealis

  ; -DDEBUG=1 ;; enable some debug assertions in the platform core
  ; -D WLED_DEBUG ; lots of generic debug messages
  ; -D SR_DEBUG ; some extra debug messages from audioreactive

  ; -D LEDPIN=27
  ; -D RLYPIN=-1
  ; -D BTNPIN=39
  ; -D IRPIN=-1 -D TEMPERATURE_PIN=-1                               ;; no default pins for IR, DallasTemp
  ; -D ENCODER_DT_PIN=-1 -D ENCODER_CLK_PIN=-1 -D ENCODER_SW_PIN=-1 ;; no default pins for Rotary
  ; -D HW_PIN_SCL=-1 -D HW_PIN_SDA=-1
  ; -D SR_DMTYPE=1 -D I2S_SDPIN=25 -D I2S_WSPIN=32 -D I2S_CKPIN=33
  ; -D SR_SQUELCH=5 -D SR_GAIN=30 -D SR_FREQ_PROF=5                 ;; ICS-4343x specific

  ; -D SR_ENABLE_DEFAULT  ;; enable at first start - no need to manually set "enable", then reboot
  
  ;; Turn off as much as possible to save space
  ${common_mm.build_disable_sync_interfaces}
  ; -D WLED_DISABLE_OTA
  
lib_ignore = IRremoteESP8266
